services:
  - type: static
    name: student-ai-hub
    env: static
    buildCommand: "" 
    publishPath: "./"
    headers:
      - path: /*
        headers:
          # These two lines "unlock" the Node Container in your browser
          - key: Cross-Origin-Embedder-Policy
            value: require-corp
          - key: Cross-Origin-Opener-Policy
            value: same-origin
