services:
  - type: web
    name: student-ai-hub
    runtime: static # This tells Render it is a Static Site, not a Node server
    buildCommand: "" 
    publishPath: "./" # or the folder where your index.html lives
    headers:
      - path: /*
        headers:
          - key: Cross-Origin-Embedder-Policy
            value: require-corp
          - key: Cross-Origin-Opener-Policy
            value: same-origin
